---
deployment:
  tasks:
    - export DEPLOYPATH=/home/allimglu/cakes.cakesandpastries.ng/
    - /opt/cpanel/composer/bin/composer install --no-dev
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
